### ISSUE TITLE
[Question] What's the difference between this modding tool and DSMapStudio

### ISSUE THREAD

**Issue by wswslzp** [vawser/Smithbox#28]
It's a fork of [DSMapStudio](https://github.com/soulsmods/DSMapStudio). So what's the difference? Any new feature than orginal one?

**Comment by vawser** [comment]
It has a lot new features, so it is difficult to summarise them into a comprehensive list, but here is a quick list:

# New Editors
- Adds a GPARAM Editor, which supports some simple mass-edit functionality.
- Adds a Texture Viewer, which supports viewing most of the textures used by the game. For icon images, it will show the actual icon ID when you hover over the icon's tile within the image.

### Map Editor
- For Elden Ring, a world map feature which lets you pick the open-world tiles from an image, narrowing down the map list to that exact tile, making it a lot easier to track which tiles are where.
- New actions, such as Replicate which make it easier to create patterns of objects, or Scramble, which lets you randomise the position, rotation and scale of select objects.
- Support for Selection Groups (groups of objects that can be re-selected with a single shortcut).
- Support for Prefabs (stored groups of objects that can be created instantly). For example, you could select all the assets within a fort, make it a prefab, and then be able to instantly re-make the fort where-ever by importing the prefab.
- Adds the "Order" action, allowing you to re-order the map objects within the map object list.

### Asset Browser
- A set of three windows that are used in the Map Editor and Model Editor. Lets you see all possible model assets in a simple fashion, categorising them into Characters, Assets, Parts and MapPieces. Each list supports aliases which makes it a lot easier to find assets during map design (e.g. you can type in rock and only assets with rock in their alias name or tags will appear)

### Param Editor
- Support for all of kinds of aliases, which are lists of IDs matched to english names. For example, instead of just seeing the event flag 9107 in the Visibility field of a ShopLineupParam row, it will tell you 9107 is the event flag for defeating Hoarah Loux
- Support for image preview for fields such as Icon ID, letting you see the actual icon instead of only the numeric ID.
- New action: "Find Instances of Value", which will find any usage of a specified value within the params.

### Text Editor
- Adds "Sync Entries" action, letting you quickly sync stuff like weapon descriptions by editing the first and then using the action, instead of requiring you to edit all 12 or so of the entries.
- Added "Search and Replace" action, providing that functionality across all text files.

**Comment by wswslzp** [comment]
Thanks for your explanation :) It helps a lot if mention it in readme. 
Closed
