### ISSUE TITLE
Can't save params

### ISSUE THREAD

**Issue by metinc** [vawser/Smithbox#30]
I just created a new project with Smithbox 1.0.13 but when I hit CTRL+S I get an error `Failed to save file: Value cannot be null. (Parameter 'path')`

![image](https://github.com/vawser/Smithbox/assets/1820121/1bc296cf-b4ba-40b8-8fa6-8ff04468fbf9)

**Comment by LibretroAdmin** [comment]
Latest commit version does not seem to save/update gparam files anymore either.

**Comment by MrRee1995** [comment]
This may be because when creating a new project, you clicked and selected the game directory of Elden's Circle first, and then selected the project directory. This may cause the project directory to be created at the root of the disk. If you see the [projct.json] file at the root of the disk, delete it to restore it.

**Comment by vawser** [comment]
These should be fixed in 1.0.14 now.
